version: 0.2

phases:
  install:
    commands:
      - echo "No dependencies to install"

  build:
    commands:
      - echo "No build step needed for a single HTML file"

artifacts:
  files:
    - 'index.html'
  discard-paths: no
